# Generated by Django 4.1.4 on 2024-05-17 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('room', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='hotel_description',
            new_name='room_description',
        ),
    ]
